services:
  - type: web
    name: snapscore-auth
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.main:app --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:10000
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_API_KEY
        sync: false
